name: My-GitHub-Actions-Basics

env:
  APPLICATION_NAME   : "MyFlask"
  DEPLOY_PACKAGE_NAME: "flask-deploy-ver-${{ github.sha }}"
  
  
on:
  push:
    branches:
      - main
  # Allows you to run this workflow manually from the Actions tab
  #workflow_dispatch:

jobs:
  my_testing:
    runs-on: ubuntu-latest
    
    steps:
    - name: Print Hello Message in Testing
      run: echo "Hello World from Testing Job"
      
    - name: Execute few commands
      run: |
        echo "Hello Message1"
        echo "Hello Message2"
        echo "Application name: ${{ env.APPLICATION_NAME }}"
    
    - name: List current folder before clone
      run: ls -la
    
    - name: Clone my repo
      uses: actions/checkout@v1
    
    - name: List current folder after clone
      run: ls -la
        
  my_deploy:
    runs-on: ubuntu-latest
    needs: [my_testing]
    env:
      VAR1: "This is Job-level Variable1"
      VAR2: "This is Job-level Variable2"
    
    steps:
    - name: Print Hello Message in Deploy
      run: echo "Hello World from Deploy Job"
      
    - name: Print env vars  
      run: |
        echo "Var1 = ${{ env.VAR1 }}"
        echo "Var2 = ${{ env.VAR2 }}"
        echo "Var3 = $LOCAL_VAR"
      env:
        LOCAL_VAR: "This is super local Env Var"
        
      
    - name: Print Deployment package
      run: echo "Deploy package name is ${{ env.DEPLOY_PACKAGE_NAME }}"
      
    - name: Test for some packages 1
      run: aws --version
      
    - name: Test for some packages 2
      run: zip --version
